### ISSUE TITLE
Q: Java 11 support for lambda-from-string?

### ISSUE THREAD

**Issue by mtaivalj** [greenjoe/lambdaFromString#10]
Only Java 8 is supported.
Are there plans to support Java 11?
Or is it impossible for some reason? Why?

**Comment by neeraj9** [comment]
@mtaivalj it will be great if you can give pointers to get this fixed for Java 11. I will be stuck if this project doesn't move to Java 11 which I need desperately.

**Comment by parry84** [comment]
It is already possible to use current lamba-from-string with Java 11 by using the JDK compiler instead of the Eclipse JDT Compiler (see Readme). Unfortunately, this imply the redistribution of the JDK (the JRE is not enough).

Recent Eclipse JDT Compiler releases (needed for Java 11) are plagued by the following open bug: https://bugs.eclipse.org/bugs/show_bug.cgi?id=541269

Waiting for the bug resolution, I created a lamba-from-string workaround that essentially creates a temporary file: https://github.com/parry84/lambdaFromString

**Comment by greenjoe** [comment]
Should be fixed in 1.7 by https://github.com/greenjoe/lambdaFromString/pull/12
